### ISSUE TITLE
Run sail npm run dev on windows

### ISSUE THREAD

**Issue by NicolasDuquesne2** [CodeReviewPals/code-review-pals#75]
Running the  dev app via sail can show issue on windows.
This issue is already known here : https://github.com/laravel/vite-plugin/issues/28
This solution should help : https://github.com/laravel/vite-plugin/issues/28#issuecomment-1169592126

**Comment by geeksesi** [comment]
Great work, Nicolas! 
Thank you so much for fixing the issue.
 Would you be able to submit a pull request with the changes to vite.config.js? 
 It would be really helpful for me to test it out that way, and hopefully, we can merge it soon. 
 
 Thanks again, I appreciate your help! ❤️

**Comment by geeksesi** [comment]
#76

**Comment by Abhi02054** [comment]
My vite localhost does not show anything there is no error in the program but my localhost does not show me the output it's blank what should I do I tried everything but it's not working.

**Comment by geeksesi** [comment]
@Abhi02054 
i need more information to help,
are you using docker? what is your node version.
do you run the PHP webserver? like `php artisan serve` or nginx or apache or others?
